services:
  mysql:
    image: mysql:8
    container_name: mysql
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: estapar
    volumes:
      - mysql-data:/var/lib/mysql

  estapar-app:
    build: .
    container_name: estapar-app
    ports:
      - "3003:3003"
    environment:
      SPRING_DATASOURCE_URL: jdbc:mysql://mysql:3306/estapar
      SPRING_DATASOURCE_USERNAME: root
      SPRING_DATASOURCE_PASSWORD: root
    depends_on:
      - mysql

  garage-sim:
    image: cfontes0estapar/garage-sim:1.0.0
    container_name: garage-sim
    ports:
      - "3000:3000"
    environment:
      - WEBHOOK_URL=http://estapar-app:3003/webhook

# ✅ Definição correta do volume abaixo
volumes:
  mysql-data:
